# Generated by Django 4.0.6 on 2022-08-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=100, null=True, upload_to='', width_field=100),
        ),
    ]
